#!/bin/sh
# SessionStart hook: print the company glossary index so every stage uses the recorded terms.
# Company from AIDLC_GLOSSARY, else <project>/.aidlc/glossary, else the `Company:` line of
# <project>/docs/repo-profile.md (virtualstock | logicbroker). off, an unknown value or no
# source prints nothing. The index is generated by scripts/build_plugin.py from the glossary.
# Oh My Pi's guard extension runs this same script so both hosts inject identical text.
ROOT="${CLAUDE_PROJECT_DIR:-$PWD}"
COMPANY="${AIDLC_GLOSSARY:-}"
[ -z "$COMPANY" ] && [ -f "$ROOT/.aidlc/glossary" ] && COMPANY=$(tr -d '[:space:]' < "$ROOT/.aidlc/glossary")
[ -z "$COMPANY" ] && [ -f "$ROOT/docs/repo-profile.md" ] && COMPANY=$(sed -n 's/^- *Company: *\([A-Za-z]*\).*/\1/p' "$ROOT/docs/repo-profile.md" | head -1)
COMPANY=$(printf '%s' "$COMPANY" | tr 'A-Z' 'a-z')
case "$COMPANY" in
  virtualstock|logicbroker) ;;
  *) exit 0 ;;
esac
if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ]; then DIR="${CLAUDE_PLUGIN_ROOT}/docs/glossary"; else DIR="$ROOT/docs/glossary"; fi
INDEX="$DIR/$COMPANY-index.md"
[ -f "$INDEX" ] || exit 0
printf '[aidlc-glossary]\n'
printf 'Company glossary: %s. Use these terms in artifacts and replies. When a change introduces a term this index lacks, list it on the glossary line of intent.md and spec.md with a one-line definition and offer an entry from %s/template.md. Full entry, usage note and evidence: %s/%s-glossary.md. Write off to .aidlc/glossary to silence this block.\n' "$COMPANY" "$DIR" "$DIR" "$COMPANY"
cat "$INDEX"
